# -----------------------------------------------------------------------------
# GitHub Actions Workflow for Java Project with Maven
# Project: BetaSolutions - Eksamensprojekt F2025 - KEA
#
# Purpose:
# - Build Java project with Maven
# - Run unit tests
# - Generate and upload Maven dependency graph (optional, continue on error)
# - Cache Maven dependencies for faster builds
# 
# Triggers:
# - Push to 'develop' branch
# - Pull Request targeting 'develop' branch
#
# Notes:
# - No deployment to Azure yet (handled in a later task)
# -----------------------------------------------------------------------------

name: Java CI with Maven

on:
  push:
    branches: 
      - develop
  pull_request:
    branches: 
      - develop

jobs:
  build-and-test:
    name: Build, Test and Generate Dependency Graph
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from GitHub
    - name: Checkout source code
      uses: actions/checkout@v4

    # Step 2: Set up Java JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Step 3: Build the project (compile code)
    - name: Compile the project
      run: mvn clean compile

    # Step 4: Run unit tests
    - name: Run unit tests
      run: mvn test

    # Step 5: Package the application (optional step to build JAR)
    - name: Package the application
      run: mvn package

    # Step 6: Try to generate Maven dependency graph (optional)
    - name: Generate Maven dependency graph
      run: mvn com.github.ferstl:depgraph-maven-plugin:aggregate
      continue-on-error: true

    # Step 7: Try to upload Maven dependency graph to GitHub (optional)
    - name: Upload Maven dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4
      continue-on-error: true
