# -----------------------------------------------------------------------------
# GitHub Actions Workflow for Integration Tests
# Project: BetaSolutions - Eksamensprojekt F2025 - KEA
#
# Purpose:
# - Run integration tests (with mvn verify) after pushing to 'main' branch
#
# Triggers:
# - Push to 'master' branch
# -----------------------------------------------------------------------------

name: Integration Tests

on:
  push:
    branches:
      - master

jobs:
  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Set up Java JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Run Maven verify (integration tests included)
      - name: Run Maven verify
        run: mvn clean verify
